# (cat 1-4), (project 1-6), en, ru — для матрицы навыков
MATRIX_ROWS = [
    ("1", "3", "JTBD & problem framing", "JTBD и постановка задачи"),
    ("1", "3", "Qualitative interviews", "Качественные интервью"),
    ("1", "3", "Survey design & analysis", "Опросы и анализ"),
    ("1", "3", "Usability lab tests", "Лабораторные юзабилити-тесты"),
    ("1", "3", "Remote moderated tests", "Удалённые модерируемые тесты"),
    ("1", "3", "Heatmaps & session replay", "Теплокарты и сессии"),
    ("1", "3", "Funnel & cohort reading", "Воронки и когорты"),
    ("1", "3", "A/B hypothesis design", "Дизайн A/B-гипотез"),
    ("1", "3", "Metric definition (North Star)", "Метрики и North Star"),
    ("1", "4", "HR workflow observation", "Наблюдение за HR-процессами"),
    ("1", "6", "Advertiser journey mapping", "Карта пути рекламодателя"),
    ("1", "2", "Platform analytics literacy", "Чтение аналитики платформы"),
    ("1", "5", "Engagement metrics design", "Метрики вовлечённости"),
    ("1", "1", "Player pain-point research", "Исследование болей игрока"),
    ("2", "2", "Design tokens & variables", "Токены и variables"),
    ("2", "2", "Atomic component libraries", "Атомарные библиотеки"),
    ("2", "2", "White-label theming", "White-label темизация"),
    ("2", "2", "Dashboard information density", "Плотность дашбордов"),
    ("2", "3", "Landing system at scale", "Лендинги в масштабе"),
    ("2", "3", "Paywall & checkout UX", "Пейволл и чекаут"),
    ("2", "2", "Checkout microcopy", "Микрокопирайт оплаты"),
    ("2", "5", "Generative UI patterns", "Генеративные UI-паттерны"),
    ("2", "5", "Gallery & social proof UI", "Галерея и соц.доказательства"),
    ("2", "4", "Warm enterprise UI", "Тёплый enterprise UI"),
    ("2", "4", "Data-dense tables", "Плотные таблицы"),
    ("2", "6", "Card-based venue selection", "Выбор площадок карточками"),
    ("2", "6", "Timeline scheduling UI", "Таймлайн публикаций"),
    ("2", "1", "Game HUD readability", "Читаемость HUD"),
    ("2", "1", "Rarity & loot clarity", "Редкость и лут"),
    ("2", "3", "Streaming & live UI", "Стриминг и live UI"),
    ("2", "2", "Icon systems at scale", "Иконсистемы в масштабе"),
    ("2", "5", "Onboarding tutorials", "Онбординг-туториалы"),
    ("2", "3", "Upsell & cross-sell patterns", "Апселл и кросс-селл"),
    ("3", "2", "Cross-functional rituals", "Кросс-функциональные ритуалы"),
    ("3", "2", "Handoff protocols", "Протоколы хэндоффа"),
    ("3", "2", "Design QA with dev", "Дизайн-QA с разработкой"),
    ("3", "3", "Roadmap alignment with PM", "Согласование роадмапа с PM"),
    ("3", "4", "Stakeholder demos", "Демо для стейкхолдеров"),
    ("3", "5", "AI pipeline rollout", "Внедрение AI-пайплайнов"),
    ("3", "1", "Live-ops design cadence", "Каденция live-ops"),
    ("3", "6", "MVP scope negotiation", "Согласование MVP"),
    ("3", "2", "Multi-product prioritization", "Приоритизация продуктов"),
    ("3", "3", "Retention loop design", "Петли retention"),
    ("3", "3", "Win-back flows", "Флоу возврата"),
    ("4", "1", "Composition & visual rhythm", "Композиция и ритм"),
    ("4", "1", "Color scripting for mood", "Цвет и настроение"),
    ("4", "5", "Character-driven layouts", "Лейауты с персонажами"),
    ("4", "6", "Illustration ↔ UI handoff", "От иллюстрации к UI"),
    ("4", "4", "Friendly data visualization", "Дружелюбная визуализация"),
    ("4", "2", "Brand stretch across 20+ SKUs", "Бренд на 20+ SKU"),
    ("4", "3", "Cinematic promo layouts", "Кинематографичные промо"),
    ("4", "5", "Motion storyboards", "Моушн-сториборды"),
    ("4", "1", "Texture & material language", "Текстуры и материалы"),
    ("4", "3", "Thumbnail & cover systems", "Системы превью и обложек"),
    ("2", "4", "Slack-first notification UX", "UX уведомлений Slack"),
    ("1", "2", "Conversion narrative testing", "Тесты конверсионного нарратива"),
    ("3", "6", "Telegram-native patterns", "Паттерны под Telegram"),
]
