# 6 проектов: расширенные тексты для попапа (3 блока EN/RU)

PROJECTS = [
    {
        "title_en": "Game UI · In-game Shop",
        "title_ru": "Game UI · Внутриигровой магазин",
        "sub_en": "Post-apocalyptic shooter · HUD, shop, inventory · 2023–2024",
        "sub_ru": "Постапокалиптический шутер · HUD, магазин, инвентарь · 2023–2024",
        "b1_en": "Full UI system for a fast-paced shooter: HUD, in-game shop, inventory, queue and trade flows. Built for extreme information density and split-second decisions under pressure.",
        "b1_ru": "Полная UI-система для динамичного шутера: HUD, внутриигровой магазин, инвентарь, очереди и торговля. Рассчитана на высокую плотность информации и решения за доли секунды.",
        "b2_en": "Designed icon set, currency loop, rarity language, and animated transitions between states — with a colorblind-safe rarity palette and scalable components for future content drops.",
        "b2_ru": "Спроектированы иконсет, экономика валюты, язык редкости и анимированные переходы — с палитрой редкостей для дальтоников и масштабируемыми компонентами под новые контент-паки.",
        "b3_en": "Accessibility and scanability were treated as core mechanics: contrast, hierarchy, and motion cues so players parse offers without leaving the flow.",
        "b3_ru": "Доступность и сканируемость как часть механики: контраст, иерархия и моушн-подсказки, чтобы игрок читал предложения, не выпадая из флоу.",
    },
    {
        "title_en": "Gate19",
        "title_ru": "Gate19",
        "sub_en": "Affiliate platform · 20+ products · MiraiTech · 2022–2025",
        "sub_ru": "Аффилиат-платформа · 20+ продуктов · MiraiTech · 2022–2025",
        "b1_en": "End-to-end design for an affiliate tooling ecosystem — from brand and marketing surfaces to dense dashboard architecture used daily by operations teams.",
        "b1_ru": "Полный цикл дизайна аффилиат-экосистемы — от маркетинговых поверхностей до плотной архитектуры дашбордов для операционных команд.",
        "b2_en": "A unified component library became the backbone for 20+ products: −60% handoff time, launches under one week, and White Label flows that reduced branded site launch to minutes.",
        "b2_ru": "Единая библиотека компонентов стала хребтом для 20+ продуктов: −60% хэндофф, запуски быстрее недели, White Label — запуск брендированного сайта за минуты.",
        "b3_en": "The system also fed an AI landing pipeline — brief to publish moved from days to hours across the portfolio. Live references: pnb.agency ecosystem.",
        "b3_ru": "Система стала основой AI-пайплайна лендингов — от брифа до публикации за часы вместо дней. Референсы экосистемы: pnb.agency.",
    },
    {
        "title_en": "JAVHD",
        "title_ru": "JAVHD",
        "sub_en": "SaaS video platform · Monetization · MiraiTech · 2022–2025",
        "sub_ru": "SaaS-видео · Монетизация · MiraiTech · 2022–2025",
        "b1_en": "UX/UI for a mature SaaS video product: seamless access to core flows, responsive layouts, and monetization surfaces tuned for conversion and retention.",
        "b1_ru": "UX/UI для зрелого SaaS-видеопродукта: бесшовный доступ к ключевым сценариям, адаптив и монетизационные экраны под конверсию и удержание.",
        "b2_en": "Beyond core flows: live streaming and private sessions, chat with tokens and gifts, curated home rails with native ad placements, advanced search and sort, and creator/studio profile pages.",
        "b2_ru": "Помимо базовых сценариев: live и приватные сессии, чат с токенами и подарками, кураторские ленты с рекламой, расширенный поиск и сортировка, страницы создателей и студий.",
        "b3_en": "Gamified tours and motion prototypes (Figma) supported motivation loops; 100+ landing variants with explicit conversion hypotheses fed a templated growth system.",
        "b3_ru": "Геймифицированные туры и моушн-прототипы в Figma усиливали мотивационные петли; 100+ лендингов с явными гипотезами конверсии стали шаблонной growth-системой.",
    },
    {
        "title_en": "Corgday HR CRM",
        "title_ru": "Corgday HR CRM",
        "sub_en": "Internal HR tooling · Hill and Company · 2022+",
        "sub_ru": "Внутренний HR · Hill and Company · 2022+",
        "b1_en": "Internal HR CRM to centralize employee data, payroll-related workflows, and performance signals in one calm, legible interface — launched in 2022 for day-to-day HR operations.",
        "b1_ru": "Внутренняя HR CRM для централизации данных сотрудников, зарплатных процессов и сигналов эффективности в одном спокойном, читаемом интерфейсе — запуск в 2022 для ежедневной работы HR.",
        "b2_en": "Complex tables and multi-step forms were reshaped around real HR processes (not the database schema). Org tree, payroll modules, and calendar fill-in patterns reduced manual work.",
        "b2_ru": "Сложные таблицы и многошаговые формы выстроены вокруг реальных HR-процессов, а не схемы БД. Древо оргструктуры, модули расчёта зарплаты и календарные сценарии сократили ручной труд.",
        "b3_en": "A Slack alert module cut manual follow-ups ~40% across the holding. Warm, approachable UI paired with optimized paths for the most frequent HR tasks.",
        "b3_ru": "Slack-алерты сократили ручные follow-up ~40% в холдинге. Тёплый UI и оптимизированные пути для самых частых HR-задач.",
    },
    {
        "title_en": "ShugarAi",
        "title_ru": "ShugarAi",
        "sub_en": "AI characters · Photo/video/audio · MiraiTech · 2023–2025",
        "sub_ru": "AI-персонажи · фото/видео/аудио · MiraiTech · 2023–2025",
        "b1_en": "Full-cycle UX for generation flows: landing variants, quizzes, surveys, banner systems for UI and ads — plus a social gallery on the home feed to drive depth of session.",
        "b1_ru": "Полный UX циклов генерации: лендинги, квизы, опросы, баннерные системы для UI и рекламы — плюс социальная галерея на главной для глубины сессии.",
        "b2_en": "Generation path includes sharing back to the feed, likes, comments, and interactive loops. Live chat and tutorial layers onboard users into complex AI tooling without friction.",
        "b2_ru": "Путь генерации включает шаринг в ленту, лайки, комментарии и интерактив. Live-чат и туториал помогают освоить сложный AI-продукт без трения.",
        "b3_en": "Focus on engagement metrics: repeat visits, session length, and return rate — with UI that keeps creative exploration fast and legible.",
        "b3_ru": "Фокус на метриках вовлечённости: возвраты, длина сессии, удержание — при UI, где творческое исследование остаётся быстрым и читаемым.",
    },
    {
        "title_en": "Adbot",
        "title_ru": "Adbot",
        "sub_en": "Telegram ad placement · 2021",
        "sub_ru": "Реклама в Telegram · 2021",
        "b1_en": "End-to-end product for advertisers: create a post, pick channels, pay, then track performance — authors onboard via Telegram bot with cards auto-imported into the service.",
        "b1_ru": "Продукт для рекламодателей: пост → выбор площадок → оплата → аналитика; авторы каналов онбордятся через бота, карточки площадок подтягиваются автоматически.",
        "b2_en": "The centerpiece is dense venue cards: stats, availability, and inline scheduling of publication time — maximum information with minimal friction at selection stage.",
        "b2_ru": "Ключевой элемент — насыщенные карточки площадок: статистика, доступность и выбор времени публикации прямо в карточке — максимум информации при минимуме трения.",
        "b3_en": "Multiple card formats for adaptive layouts, promo surfaces, and quick time-slot selection — logo, flows, web + mobile prototypes shipped as one coherent system.",
        "b3_ru": "Несколько форматов карточек под адаптив, промо-поверхности и быстрый выбор слота — логотип, флоу, веб и мобайл как единая система.",
    },
]
